
[colors.bright]
black = "#666666"
blue = "#7aa6da"
cyan = "#54ced6"
green = "#9ec400"
magenta = "#b77ee0"
red = "#ff3334"
white = "#2a2a2a"
yellow = "#e7c547"

[colors.normal]
black = "#000000"
blue = "#7aa6da"
cyan = "#70c0ba"
green = "#b9ca4a"
magenta = "#c397d8"
red = "#d54e53"
white = "#424242"
yellow = "#e6c547"

[colors.primary]
background = "#000000"
foreground = "#eaeaea"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "HackGen35 Console"
style = "Bold"

[font.bold_italic]
family = "HackGen35 Console"
style = "Bold Italic"

[font.italic]
family = "HackGen35 Console"
style = "Italic"

[font.normal]
family = "HackGen35 Console NF"
style = "Regular"

[selection]
save_to_clipboard = true

[window]
startup_mode = "Maximized"

[window.padding]
x = 5
y = 5

[general]
live_config_reload = true

